const WatchesData = [
    {
        parentId: 1,
        img: './rich-tales/watches/invicta-in8.png',
        brandimg: './rich-tales/brands-images/invicta-brand.png',
        title: 'Invicta IN8927OB',
        price: 18360,
        filters: [
            {key: 'Пол', keyText: 'Мужской'},
            {key: 'Бренд', keyText: 'Invicta'},
            {key: 'Страна', keyText: 'Швейцария'},
            {key: 'Материал', keyText: 'Металл'},
            {key: 'Цвет', keyText: 'Белый'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Классический'},
        ]
    },
    {
        parentId: 2,
        img: './rich-tales/watches/ck-k8q.png',
        brandimg: './rich-tales/brands-images/ck-brand.png',
        title: 'Calvin Klein K8Q336X2',
        price: 17900,
        filters: [
            {key: 'Пол', keyText: 'Женский'},
            {key: 'Бренд', keyText: 'Calvin Klein'},
            {key: 'Страна', keyText: 'США'},
            {key: 'Материал', keyText: 'Металл'},
            {key: 'Цвет', keyText: 'Белый'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Классический'},
        ]
    },
    {
        parentId: 3,
        img: './rich-tales/watches/casio-gsh.png',
        brandimg: './rich-tales/brands-images/casio-brand.png',
        title: 'Casio G-SHOCK GA-2100SKE-7AER',
        price: 11900,
        filters: [
            {key: 'Пол', keyText: 'Мужской'},
            {key: 'Бренд', keyText: 'Casio'},
            {key: 'Страна', keyText: 'Япония'},
            {key: 'Материал', keyText: 'Сталь'},
            {key: 'Цвет', keyText: 'Синий'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Механический'},
        ]
    },
    {
        parentId: 4,
        img: './rich-tales/watches/rodania-r11.png',
        brandimg: './rich-tales/brands-images/rodania-brand.png',
        title: 'Rodania R11001',
        price: 19850,
        filters: [
            {key: 'Пол', keyText: 'Мужской'},
            {key: 'Бренд', keyText: 'Rodania'},
            {key: 'Страна', keyText: 'Швейцария'},
            {key: 'Материал', keyText: 'Металл'},
            {key: 'Цвет', keyText: 'Белый'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Классический'},
        ]
    },
    {
        parentId: 5,
        img: './rich-tales/watches/seiko-ssb.png',
        brandimg: './rich-tales/brands-images/seiko-brand.png',
        title: 'Seiko SSB405P1',
        price: 37660,
        filters: [
            {key: 'Пол', keyText: 'Мужской'},
            {key: 'Бренд', keyText: 'Seiko'},
            {key: 'Страна', keyText: 'Япония'},
            {key: 'Материал', keyText: 'Сталь'},
            {key: 'Цвет', keyText: 'Белый'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Механический'},
        ]
    },
    {
        parentId: 6,
        img: './rich-tales/watches/davosa-161.png',
        brandimg: './rich-tales/brands-images/davosa-brand.png',
        title: 'DAVOSA DAV.16152740',
        price: 114760,
        filters: [
            {key: 'Пол', keyText: 'Мужской'},
            {key: 'Бренд', keyText: 'Davosa'},
            {key: 'Страна', keyText: 'Швейцария'},
            {key: 'Материал', keyText: 'Серебро'},
            {key: 'Цвет', keyText: 'Синий'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Классический'},
        ]
    },
    {
        parentId: 7,
        img: './rich-tales/watches/hublot-gold.png',
        brandimg: './rich-tales/brands-images/hublot-brand.png',
        title: 'HUBLOT Gold Diamonds',
        price: 2970000,
        filters: [
            {key: 'Пол', keyText: 'Женский'},
            {key: 'Бренд', keyText: 'HUBLOT'},
            {key: 'Страна', keyText: 'Швейцария'},
            {key: 'Материал', keyText: 'Золото'},
            {key: 'Цвет', keyText: 'Черный'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Классический'},
        ]
    },
    {
        parentId: 8,
        img: './rich-tales/watches/omega-210.png',
        brandimg: './rich-tales/brands-images/omega-brand.png',
        title: 'OMEGA 21032422004001',
        price: 610000,
        filters: [
            {key: 'Пол', keyText: 'Мужской'},
            {key: 'Бренд', keyText: 'Omega'},
            {key: 'Страна', keyText: 'Швейцария'},
            {key: 'Материал', keyText: 'Титан'},
            {key: 'Цвет', keyText: 'Черный'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Механический'},
        ]
    },
    {
        parentId: 9,
        img: './rich-tales/watches/cartier-tnk.png',
        brandimg: './rich-tales/brands-images/cartier-brand.png',
        title: 'CARTIER TANK ANGLAISE',
        price: 902000,
        filters: [
            {key: 'Пол', keyText: 'Женский'},
            {key: 'Бренд', keyText: 'Cartier'},
            {key: 'Страна', keyText: 'Франция'},
            {key: 'Материал', keyText: 'Золото'},
            {key: 'Цвет', keyText: 'Белый'},
            {key: 'Форма', keyText: 'Прямоугольная'},
            {key: 'Циферблат', keyText: 'Классический'},
        ]
    },
    {
        parentId: 10,
        img: './rich-tales/watches/seiko-ssb8.png',
        brandimg: './rich-tales/brands-images/seiko-brand.png',
        title: 'Seiko SSB321P1',
        price: 37710,
        filters: [
            {key: 'Пол', keyText: 'Мужской'},
            {key: 'Бренд', keyText: 'Seiko'},
            {key: 'Страна', keyText: 'Япония'},
            {key: 'Материал', keyText: 'Серебро'},
            {key: 'Цвет', keyText: 'Синий'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Механический'},
        ]
    },
    {
        parentId: 11,
        img: './rich-tales/watches/davosa-1615.png',
        brandimg: './rich-tales/brands-images/davosa-brand.png',
        title: 'DAVOSA DAV.16151174',
        price: 74015,
        filters: [
            {key: 'Пол', keyText: 'Мужской'},
            {key: 'Бренд', keyText: 'Davosa'},
            {key: 'Страна', keyText: 'Швейцария'},
            {key: 'Материал', keyText: 'Серебро'},
            {key: 'Цвет', keyText: 'Зеленый'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Классический'},
        ]
    },
    {
        parentId: 12,
        img: './rich-tales/watches/ck-2520.png',
        brandimg: './rich-tales/brands-images/ck-brand.png',
        title: 'Calvin Klein 25200230',
        price: 21000,
        filters: [
            {key: 'Пол', keyText: 'Женский'},
            {key: 'Бренд', keyText: 'Calvin Klein'},
            {key: 'Страна', keyText: 'США'},
            {key: 'Материал', keyText: 'Металл'},
            {key: 'Цвет', keyText: 'Синий'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Классический'},
        ]
    },
    {
        parentId: 13,
        img: './rich-tales/watches/rodania-r200.png',
        brandimg: './rich-tales/brands-images/rodania-brand.png',
        title: 'Rodania R20005',
        price: 21000,
        filters: [
            {key: 'Пол', keyText: 'Мужской'},
            {key: 'Бренд', keyText: 'Rodania'},
            {key: 'Страна', keyText: 'Швейцария'},
            {key: 'Материал', keyText: 'Серебро'},
            {key: 'Цвет', keyText: 'Зеленый'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Механический'},
        ]
    },
    {
        parentId: 14,
        img: './rich-tales/watches/invicta-in29.png',
        brandimg: './rich-tales/brands-images/invicta-brand.png',
        title: 'Invicta IN29372',
        price: 13000,
        filters: [
            {key: 'Пол', keyText: 'Мужской'},
            {key: 'Бренд', keyText: 'Invicta'},
            {key: 'Страна', keyText: 'Швейцария'},
            {key: 'Материал', keyText: 'Серебро'},
            {key: 'Цвет', keyText: 'Черный'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Классический'},
        ]
    },
    {
        parentId: 15,
        img: './rich-tales/watches/casio-efv.png',
        brandimg: './rich-tales/brands-images/casio-brand.png',
        title: 'Casio Edifice EFV-600D-2AVUEF',
        price: 12210,
        filters: [
            {key: 'Пол', keyText: 'Мужской'},
            {key: 'Бренд', keyText: 'Casio'},
            {key: 'Страна', keyText: 'Япония'},
            {key: 'Материал', keyText: 'Сталь'},
            {key: 'Цвет', keyText: 'Синий'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Механический'},
        ]
    },
    {
        parentId: 16,
        img: './rich-tales/watches/rodania-r15.png',
        brandimg: './rich-tales/brands-images/rodania-brand.png',
        title: 'Rodania R15006',
        price: 24600,
        filters: [
            {key: 'Пол', keyText: 'Мужской'},
            {key: 'Бренд', keyText: 'Rodania'},
            {key: 'Страна', keyText: 'Швейцария'},
            {key: 'Материал', keyText: 'Сталь'},
            {key: 'Цвет', keyText: 'Белый'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Классический'},
        ]
    },
    {
        parentId: 17,
        img: './rich-tales/watches/hublot-orl.png',
        brandimg: './rich-tales/brands-images/hublot-brand.png',
        title: 'Orlinski King Gold Pavé',
        price: 5057000,
        filters: [
            {key: 'Пол', keyText: 'Мужской'},
            {key: 'Бренд', keyText: 'HUBLOT'},
            {key: 'Страна', keyText: 'Швейцария'},
            {key: 'Материал', keyText: 'Золото'},
            {key: 'Цвет', keyText: 'Черный'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Классический'},
        ]
    },
    {
        parentId: 18,
        img: './rich-tales/watches/cartier-cle.png',
        brandimg: './rich-tales/brands-images/cartier-brand.png',
        title: 'CLE DE CARTIER',
        price: 276000,
        filters: [
            {key: 'Пол', keyText: 'Женский'},
            {key: 'Бренд', keyText: 'Cartier'},
            {key: 'Страна', keyText: 'Франция'},
            {key: 'Материал', keyText: 'Титан'},
            {key: 'Цвет', keyText: 'Белый'},
            {key: 'Форма', keyText: 'Овальная'},
            {key: 'Циферблат', keyText: 'Классический'},
        ]
    },
    {
        parentId: 19,
        img: './rich-tales/watches/rodania-r16.png',
        brandimg: './rich-tales/brands-images/rodania-brand.png',
        title: 'Rodania R16021',
        price: 25500,
        filters: [
            {key: 'Пол', keyText: 'Мужской'},
            {key: 'Бренд', keyText: 'Rodania'},
            {key: 'Страна', keyText: 'Швейцария'},
            {key: 'Материал', keyText: 'Серебро'},
            {key: 'Цвет', keyText: 'Черный'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Механический'},
        ]
    },
    {
        parentId: 20,
        img: './rich-tales/watches/casio-gmw.png',
        brandimg: './rich-tales/brands-images/casio-brand.png',
        title: 'Casio G-SHOCK GMW-B5000D-1E',
        price: 79900,
        filters: [
            {key: 'Пол', keyText: 'Мужской'},
            {key: 'Бренд', keyText: 'Casio'},
            {key: 'Страна', keyText: 'Япония'},
            {key: 'Материал', keyText: 'Серебро'},
            {key: 'Цвет', keyText: 'Белый'},
            {key: 'Форма', keyText: 'Квадратная'},
            {key: 'Циферблат', keyText: 'Механический'},
        ]
    },
    {
        parentId: 21,
        img: './rich-tales/watches/omega-300.png',
        brandimg: './rich-tales/brands-images/omega-brand.png',
        title: 'DIVER 300M CO‑AXIAL 43.5 MM', 
        price: 1205000,
        filters: [
            {key: 'Пол', keyText: 'Мужской'},
            {key: 'Бренд', keyText: 'Omega'},
            {key: 'Страна', keyText: 'Швейцария'},
            {key: 'Материал', keyText: 'Титан'},
            {key: 'Цвет', keyText: 'Черный'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Классический'},
        ]
    },
    {
        parentId: 22,
        img: './rich-tales/watches/invicta-143.png',
        brandimg: './rich-tales/brands-images/invicta-brand.png',
        title: 'Invicta IN14361', 
        price: 12900,
        filters: [
            {key: 'Пол', keyText: 'Женский'},
            {key: 'Бренд', keyText: 'Invicta'},
            {key: 'Страна', keyText: 'Швейцария'},
            {key: 'Материал', keyText: 'Сталь'},
            {key: 'Цвет', keyText: 'Синий'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Классический'},
        ]
    },
    {
        parentId: 23,
        img: './rich-tales/watches/ck-252.png',
        brandimg: './rich-tales/brands-images/ck-brand.png',
        title: 'Calvin Klein 25200267', 
        price: 26900,
        filters: [
            {key: 'Пол', keyText: 'Мужской'},
            {key: 'Бренд', keyText: 'Calvin Klein'},
            {key: 'Страна', keyText: 'США'},
            {key: 'Материал', keyText: 'Сталь'},
            {key: 'Цвет', keyText: 'Черный'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Механический'},
        ]
    },
    {
        parentId: 24,
        img: './rich-tales/watches/davosa-167.png', 
        brandimg: './rich-tales/brands-images/davosa-brand.png', 
        title: 'DAVOSA DAV.16756215', 
        price: 22410, 
        filters: [
            {key: 'Пол', keyText: 'Женский'}, 
            {key: 'Бренд', keyText: 'Davosa'},
            {key: 'Страна', keyText: 'Швейцария'},
            {key: 'Материал', keyText: 'Золото'},
            {key: 'Цвет', keyText: 'Белый'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Классический'},
        ]
    },
    {
        parentId: 25,
        img: './rich-tales/watches/seiko-sur.png', 
        brandimg: './rich-tales/brands-images/seiko-brand.png', 
        title: 'Seiko SUR416', 
        price: 34016, 
        filters: [
            {key: 'Пол', keyText: 'Женский'}, 
            {key: 'Бренд', keyText: 'Seiko'},
            {key: 'Страна', keyText: 'Япония'},
            {key: 'Материал', keyText: 'Серебро'},
            {key: 'Цвет', keyText: 'Белый'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Классический'},
        ]
    },
    {
        parentId: 26,
        img: './rich-tales/watches/cartier-bleu.png', 
        brandimg: './rich-tales/brands-images/cartier-brand.png', 
        title: 'BALLON BLEU DE CARTIER', 
        price: 1540000, 
        filters: [
            {key: 'Пол', keyText: 'Женский'}, 
            {key: 'Бренд', keyText: 'Cartier'},
            {key: 'Страна', keyText: 'Франция'},
            {key: 'Материал', keyText: 'Золото'},
            {key: 'Цвет', keyText: 'Белый'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Классический'},
        ]
    },
    {
        parentId: 27,
        img: './rich-tales/watches/hublot-dial.png', 
        brandimg: './rich-tales/brands-images/hublot-brand.png', 
        title: 'Titanium Black Shiny Dial', 
        price: 1475500, 
        filters: [
            {key: 'Пол', keyText: 'Мужской'}, 
            {key: 'Бренд', keyText: 'HUBLOT'},
            {key: 'Страна', keyText: 'Швейцария'},
            {key: 'Материал', keyText: 'Титан'},
            {key: 'Цвет', keyText: 'Черный'},
            {key: 'Форма', keyText: 'Круглая'},
            {key: 'Циферблат', keyText: 'Механический'},
        ]
    },
]

export default WatchesData